feat: added header.
ccetacm/ACM-Website-2024 pull request #1
Opened 2023-10-25 16:56 UTC by Sahil2004

# Description

Added the header/navbar of the website.

# Reference

Normal state:
![image](https://github.com/saketsarin/ACM-Website-2023/assets/40143545/65fe4993-4731-47e9-9a7a-445be4d271b3)
Hover state:
![image](https://github.com/saketsarin/ACM-Website-2023/assets/40143545/03a857fe-2d9f-46bc-9a73-7ec585d0d806)

2023-10-25 17:14 UTC, ccetacm requested changes

2023-10-25 17:14 UTC, ccetacm commented on css/styles.css
please use 2 spaces for indentation in html and css files and push in a new commit

2023-10-25 18:28 UTC, Sahil2004 commented on css/styles.css
Fixed.

2023-10-25 19:16 UTC, ccetacm requested changes
please review the design again. the nav elements should be uppercase now

2023-10-26 16:40 UTC, Sahil2004 commented
> please review the design again. the nav elements should be uppercase now

Done.

2023-11-11 17:50 UTC, closed without merging